import { expect, test } from "@playwright/test";
import { failOnConsoleErrors, login } from "./support/auth.js";

test("editor conserva listas, cursor, recursos y PDF multipágina", async ({ page }, testInfo) => {
    test.setTimeout(150_000);
    const assertConsole = await failOnConsoleErrors(page);
    await login(page);
    await page.goto("/plantillas-documentos");
    await page.getByRole("button", {name: "Nueva plantilla"}).click();
    await page.getByLabel("Nombre *").fill("Editor ampliado QA");
    await page.getByLabel("Clave *").fill("editor-ampliado-qa");
    const editor = page.locator(".ql-editor:visible");
    await editor.fill("Primero\nSegundo");
    await editor.press("ControlOrMeta+a");
    await page.getByRole("button", {name: "Lista con viñetas", exact: true}).click();
    await expect(editor.locator('li[data-list="bullet"]')).toHaveCount(2);
    await editor.click();
    await editor.press("ControlOrMeta+Home");
    await page.getByRole("button", {name: /Correo de la empresa/}).click();
    await expect(editor).toContainText("{{empresa.email}}Primero");
    await page.getByRole("button", {name: "Deshacer", exact: true}).click();
    await expect(editor).not.toContainText("{{empresa.email}}");
    await page.getByRole("button", {name: "Rehacer", exact: true}).click();
    await expect(editor).toContainText("{{empresa.email}}Primero");

    await page.getByRole("button", {name: "Encabezado", exact: true}).click();
    await editor.fill("Empresa sintética");
    await editor.press("ControlOrMeta+a");
    await page.locator(".ql-font .ql-picker-label:visible").click();
    await page.locator('.ql-font .ql-picker-item[data-value="serif"]:visible').click();
    await page.getByRole("button", {name:"Negrita",exact:true}).click();
    await expect(editor.locator("strong.ql-font-serif, strong .ql-font-serif, .ql-font-serif strong")).toContainText("Empresa sintética");
    await editor.press("ControlOrMeta+End");
    await editor.press("Enter");
    await expect(editor).toContainText("Empresa sintética");
    await page.getByRole("button", {name: "Imagen", exact: true}).click();
    const png = await page.evaluate(() => { const canvas = document.createElement("canvas"); canvas.width = 80; canvas.height = 20; const ctx = canvas.getContext("2d"); ctx.fillStyle = "#08916b"; ctx.fillRect(0,0,80,20); return canvas.toDataURL("image/png").split(",")[1]; });
    await page.getByLabel("Subir imagen a la biblioteca").setInputFiles({name: "logo-qa.png", mimeType: "image/png", buffer: Buffer.from(png, "base64")});
    await expect(editor.locator("img[data-recurso-id]")).toHaveCount(1);
    await editor.locator("img").click();
    await page.getByLabel("Ancho de imagen (px)").fill("120");
    await page.getByLabel("Ancho de imagen (px)").press("Tab");
    await expect(editor.locator("img")).toHaveAttribute("width", "120");
    await expect(editor).toContainText("Empresa sintética");
    const resourceId = await editor.locator("img").getAttribute("data-recurso-id");
    await page.getByRole("button", {name: "Contenido", exact: true}).click();
    await expect(editor.locator('li[data-list="bullet"]')).toHaveCount(2);
    await editor.press("ControlOrMeta+End");
    await editor.press("Enter"); await editor.press("Enter");
    await page.getByRole("button", {name: "Salto de página", exact: true}).click();
    await editor.press("ArrowRight");
    await editor.press("Enter");
    await page.keyboard.insertText("Segunda página: acentos áéíóú, cliente {{cliente.nombre_completo}}.");
    await page.getByRole("button", {name: "Imagen", exact: true}).click();
    await page.getByRole("button", {name: "Insertar logo-qa", exact: true}).click();
    await expect(editor.locator(`img[data-recurso-id="${resourceId}"]`)).toHaveCount(1);
    await page.getByLabel("Marca de agua (opcional)").fill("PRUEBA QA");
    await page.getByRole("button", {name: "Previsualizar cambios"}).click();
    await expect(page.getByLabel("Previsualización segura de la plantilla")).toBeVisible({timeout: 40_000});
    await expect(page.getByText("Página 1 / 2", {exact:true})).toBeVisible();
    await page.getByRole("button", {name: "Página siguiente", exact: true}).click();
    await expect(page.getByLabel("Previsualización segura de la plantilla")).toContainText("María Ejemplo López", {timeout: 10_000});
    await expect(page.getByLabel("Previsualización segura de la plantilla")).toContainText("PRUEBA QA");
    await expect(page.getByLabel("Previsualización segura de la plantilla")).toContainText("Empresa sintética");
    await expect(page.getByLabel("Previsualización segura de la plantilla")).toContainText("Generado el");
    for (let step = 0; step < 5; step++) await page.getByRole("button", {name:"Alejar PDF"}).click();
    await testInfo.attach("pdf-pagina-2", {body: await page.screenshot(), contentType: "image/png"});
    await page.keyboard.press("Escape");
    await expect(page.getByRole("dialog", {name:"Previsualización de plantilla"})).not.toBeVisible();
    await expect(page.locator("#template-editor")).toBeVisible();
    await page.getByRole("button", {name: "Guardar borrador"}).click();
    await expect(page.getByText("Plantilla creada", {exact:true})).toBeVisible();
    await page.getByRole("button", {name: "Editar", exact:true}).click();
    await expect(editor.locator('li[data-list="bullet"]')).toHaveCount(2);
    await expect(editor.locator(`img[data-recurso-id="${resourceId}"]`)).toHaveCount(1);
    await expect(page.getByLabel("Marca de agua (opcional)")).toHaveValue("PRUEBA QA");
    await testInfo.attach("editor", {body: await page.screenshot(), contentType: "image/png"});
    await page.getByRole("button", {name: "Cancelar", exact:true}).click();
    await expect(page.locator("#template-editor")).not.toBeVisible();
    await page.setViewportSize({width:390,height:844});
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await testInfo.attach("catalogo-movil", {body: await page.screenshot({fullPage:true}), contentType:"image/png"});
    assertConsole();
});
