import { expect, test } from "@playwright/test";
import { failOnConsoleErrors, login } from "./support/auth.js";

test("crea, reanuda y envía una solicitud sin aprobar ni consultar SIC", async ({ page }, testInfo) => {
    await login(page);
    const assertNoConsoleErrors = await failOnConsoleErrors(page);
    await page.goto("/solicitudes/create");
    await page.getByLabel("Cliente (obligatorio)").fill("Ma");
    await page.getByRole("option").first().click();
    await page.getByRole("button", { name: "Guardar borrador", exact: true }).click();
    await expect(page).toHaveURL(/\/solicitudes\/\d+$/);
    const detail = page.url();
    await page.getByRole("button", { name: "Enviar a revisión", exact: true }).click();
    await expect(page.getByText("Completa este dato antes de enviar la solicitud a revisión.")).toBeVisible();
    await page.getByRole("link", { name: "Completar borrador" }).click();
    await page.getByLabel("Producto y versión", { exact: true }).click();
    await page.getByRole("option", { name: /Crédito Simple Esencial/ }).click();
    await page.getByLabel("Monto solicitado (MXN)").fill("10000.00");
    await page.getByLabel("Periodicidad", { exact: true }).click();
    await page.getByRole("option", { name: "mensual", exact: true }).click();
    await page.getByLabel("Número de pagos").fill("12");
    await page.getByLabel("Amortización", { exact: true }).click();
    await page.getByRole("option", { name: "Cuota nivelada", exact: true }).click();
    const date = new Date();
    date.setDate(date.getDate() + 7);
    await page.getByLabel("Fecha estimada de desembolso").fill(date.toISOString().slice(0, 10));
    await page.getByLabel("Destino del crédito").fill("Equipo de trabajo E2E.");
    await page.getByRole("button", { name: "Guardar borrador", exact: true }).click();
    await expect(page).toHaveURL(detail);
    await page.getByRole("button", { name: "Enviar a revisión", exact: true }).click();
    await expect(page.getByRole("heading", { name: "En revisión", exact: true })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Revisión 1 conservada" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Enviar a revisión", exact: true })).toHaveCount(0);
    await page.getByLabel("Resultado de evaluación", { exact: true }).click();
    await page.getByRole("option", { name: "Favorable", exact: true }).click();
    await page.getByLabel("Metodología y versión utilizadas (evaluacion)", { exact: true }).fill("Manual de evaluación E2E versión 1");
    await page.getByLabel("Fuentes y evidencias revisadas (evaluacion)", { exact: true }).fill("Documentos del expediente y entrevista de prueba E2E.");
    await page.getByLabel("Fundamento reservado (evaluacion)", { exact: true }).fill("Evaluación manual preliminar favorable únicamente para el recorrido de pruebas.");
    await page.getByRole("button", { name: "Registrar evaluación", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Favorable · Último de la revisión actual", exact: true })).toBeVisible();
    await page.getByLabel("Resultado PLD", { exact: true }).click();
    await page.getByRole("option", { name: "Bloqueada para seguimiento", exact: true }).click();
    await page.getByLabel("Nivel de riesgo", { exact: true }).click();
    await page.getByRole("option", { name: "Alto", exact: true }).click();
    await page.getByLabel("Metodología y versión utilizadas (pld)", { exact: true }).fill("Metodología PLD E2E versión 1");
    await page.getByLabel("Fuentes y evidencias revisadas (pld)", { exact: true }).fill("Expediente y fuentes manuales de prueba E2E.");
    await page.getByLabel("Fundamento reservado (pld)", { exact: true }).fill("Se requiere aclarar información de prueba antes de concluir la revisión manual.");
    await page.getByRole("button", { name: "Registrar revisión PLD", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Bloqueada para seguimiento · Último de la revisión actual", exact: true })).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath("solicitud-revision-desktop.png"), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.getByRole("heading", { name: /Solicitud SOL-/ })).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath("solicitud-revision-mobile.png"), fullPage: true, animations: "disabled" });
    await page.getByLabel("Acción", { exact: true }).click();
    await page.getByRole("option", { name: "Devolver para corrección", exact: true }).click();
    await page.getByLabel("Motivo operativo", { exact: true }).fill("Precisar el destino de los recursos para la revisión.");
    await page.getByRole("button", { name: "Confirmar devolución", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Devuelta para corrección", exact: true })).toBeVisible();
    await page.getByRole("link", { name: "Corregir solicitud", exact: true }).click();
    await page.getByLabel("Destino del crédito").fill("Compra de herramienta y equipo de taller E2E.");
    await page.getByRole("button", { name: "Guardar borrador", exact: true }).click();
    await page.getByRole("button", { name: "Enviar a revisión", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Revisión 2 conservada", exact: true })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Favorable · Histórico; no aplica a la revisión actual", exact: true })).toBeVisible();
    await page.goto("/mi-trabajo");
    await expect(page.getByRole("link", { name: /SOL-/ }).first()).toBeVisible();
    await page.goto(detail);
    await page.getByLabel("Acción", { exact: true }).click();
    await page.getByRole("option", { name: "Rechazar solicitud", exact: true }).click();
    await page.getByLabel("Motivo operativo", { exact: true }).fill("Solicitud rechazada para verificar el cierre del recorrido E2E.");
    await page.getByRole("button", { name: "Confirmar rechazo", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Rechazada", exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Asignar responsable", exact: true })).toHaveCount(0);
    await page.screenshot({ path: testInfo.outputPath("solicitud-cierre-mobile.png"), fullPage: true, animations: "disabled" });
    assertNoConsoleErrors();
});
