import { expect, test } from "@playwright/test";
import { failOnConsoleErrors, login } from "./support/auth.js";

test("crea, reanuda y envía una solicitud sin aprobar ni consultar SIC", async ({ page }, testInfo) => {
    await login(page);
    const assertNoConsoleErrors = await failOnConsoleErrors(page);
    await page.goto("/solicitudes/create");
    await page.getByLabel("Cliente (obligatorio)").fill("Ma");
    await page.getByRole("option").first().click();
    await page.getByRole("button", { name: "Guardar borrador", exact: true }).click();
    await expect(page).toHaveURL(/\/solicitudes\/\d+$/);
    const detail = page.url();
    await page.getByRole("button", { name: "Enviar a revisión", exact: true }).click();
    await expect(page.getByText("Completa este dato antes de enviar la solicitud a revisión.")).toBeVisible();
    await page.getByRole("link", { name: "Completar borrador" }).click();
    await page.getByLabel("Producto y versión", { exact: true }).click();
    await page.getByRole("option", { name: /Crédito Simple Esencial/ }).click();
    await page.getByLabel("Monto solicitado (MXN)").fill("10000.00");
    await page.getByLabel("Periodicidad", { exact: true }).click();
    await page.getByRole("option", { name: "mensual", exact: true }).click();
    await page.getByLabel("Número de pagos").fill("12");
    await page.getByLabel("Amortización", { exact: true }).click();
    await page.getByRole("option", { name: "Cuota nivelada", exact: true }).click();
    const date = new Date();
    date.setDate(date.getDate() + 7);
    await page.getByLabel("Fecha estimada de desembolso").fill(date.toISOString().slice(0, 10));
    await page.getByLabel("Destino del crédito").fill("Equipo de trabajo E2E.");
    await page.getByRole("button", { name: "Guardar borrador", exact: true }).click();
    await expect(page).toHaveURL(detail);
    await page.getByRole("button", { name: "Enviar a revisión", exact: true }).click();
    await expect(page.getByRole("heading", { name: "En revisión", exact: true })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Revisión 1 conservada" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Enviar a revisión", exact: true })).toHaveCount(0);
    await page.screenshot({ path: testInfo.outputPath("solicitud-revision-desktop.png"), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.getByRole("heading", { name: /Solicitud SOL-/ })).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath("solicitud-revision-mobile.png"), fullPage: true, animations: "disabled" });
    await page.goto("/mi-trabajo");
    await expect(page.getByRole("link", { name: /SOL-/ }).first()).toBeVisible();
    assertNoConsoleErrors();
});
