import { test, expect } from "@playwright/test";
import { login, failOnConsoleErrors } from "./support/auth.js";

test("dual bloquea capturista y permite aprobar a otra persona sin superadmin", async ({ page, browser }, testInfo) => {
    test.setTimeout(150_000);
    test.skip(process.env.E2E_ORIGINACION_DUAL !== "true", "Requiere escenario aislado con aprobación habilitada expresamente.");
    const assertConsole = await failOnConsoleErrors(page);
    await login(page, { email: "captura.dual@example.test", password: "password" });
    await page.goto("/solicitudes");
    await page.getByRole("link", { name: /^SOL-/ }).first().click();
    await expect(page).toHaveURL(/\/solicitudes\/\d+$/);
    const detalle = page.url();
    await expect(page.getByText("En modalidad dual debe aprobar una persona que no haya capturado ni enviado la solicitud.", { exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Confirmar aprobación" })).toBeDisabled();
    await page.screenshot({ path: testInfo.outputPath("dual-capturista.png"), fullPage: true });
    const context = await browser.newContext({ baseURL: new URL(detalle).origin, locale: "es-MX" });
    try {
        const aprobador = await context.newPage();
        aprobador.setDefaultTimeout(15000);
        const assertApproverConsole = await failOnConsoleErrors(aprobador);
        await login(aprobador, { email: "aprobacion.dual@example.test", password: "password" });
        await aprobador.goto(detalle);
        await expect(aprobador.getByRole("button", { name: "Confirmar aprobación" })).toBeEnabled();
        await expect(aprobador.getByRole("heading", { name: "Evaluación manual preliminar" })).toHaveCount(0);
        await expect(aprobador.getByRole("heading", { name: "Revisión PLD" })).toHaveCount(0);
        await aprobador.getByLabel("Motivo de aprobación").fill("Aprobación dual sintética verificada por una segunda persona.");
        await aprobador.getByRole("button", { name: "Confirmar aprobación" }).click();
        await expect(aprobador.getByRole("heading", { name: "Aprobada", exact: true })).toBeVisible();
        await aprobador.screenshot({ path: testInfo.outputPath("dual-aprobada.png"), fullPage: true });
        await aprobador.getByRole("link", { name: "Contrato y tabla de pagos" }).click();
        await expect(aprobador.getByRole("heading", { name: "Contrato y tabla de pagos", exact: true })).toBeVisible();
        await aprobador.getByRole("button", { name: "Preparar contrato QA", exact: true }).click();
        await aprobador.getByLabel("Plantilla de contrato").click();
        await aprobador.getByRole("option").first().click();
        await aprobador.getByRole("checkbox").check();
        await aprobador.getByRole("button", { name: "Confirmar preparación QA" }).click();
        await expect(aprobador.getByRole("button", { name: "Ver PDF QA" })).toBeVisible({ timeout: 60000 });
        await expect(aprobador.getByText("Aprobada · sin formalizar", { exact: true })).toBeVisible();
        await expect(aprobador.getByRole("heading", { name: "Tabla congelada · con impuestos proyectados" })).toBeVisible();
        await expect(aprobador.getByRole("columnheader", { name: "Impuestos", exact: true })).toBeVisible();
        await aprobador.getByText("Ver desglose fiscal por periodo y concepto", { exact: true }).click();
        await expect(aprobador.getByText("Configuración de prueba / QA", { exact: true })).toBeVisible();
        await aprobador.screenshot({ path: testInfo.outputPath("paquete-qa-desktop.png"), fullPage: true });
        await aprobador.setViewportSize({ width: 390, height: 844 });
        await expect.poll(() => aprobador.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
        await aprobador.screenshot({ path: testInfo.outputPath("paquete-qa-mobile.png"), fullPage: true });
        await aprobador.setViewportSize({ width: 1440, height: 1000 });
        await aprobador.getByRole("button", { name: "Ver PDF QA" }).click();
        await expect(aprobador.getByRole("dialog").last()).toBeVisible();
        await expect(aprobador.locator('iframe[title^="PDF:"]')).toBeVisible();
        await expect(aprobador.getByText("No fue posible cargar", { exact: false })).toHaveCount(0);
        const pdfUrl = await aprobador.getByRole("link", { name: "Descargar", exact: true }).getAttribute("href");
        const pdf = await aprobador.request.get(pdfUrl);
        expect(pdf.ok()).toBe(true);
        const original = await pdf.body();
        await aprobador.keyboard.press("Escape");
        const fechaFirma = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Mexico_City" }).format(new Date());
        async function recibirCopia(intent) {
            await aprobador.getByRole("button", { name: "Recibir copia firmada", exact: true }).click();
            await aprobador.getByLabel("Contrato firmado en PDF").setInputFiles({
                name: "firma-sintetica-qa.pdf", mimeType: "application/pdf",
                buffer: Buffer.concat([original, Buffer.from("\n% Evidencia sintetica de firma QA intento " + intent)]),
            });
            await aprobador.getByLabel("Fecha de firma", { exact: false }).fill(fechaFirma);
            await aprobador.getByRole("checkbox").check();
            await aprobador.getByRole("button", { name: "Enviar copia para revisión" }).click();
            await expect(aprobador.getByRole("button", { name: "Revisar firma", exact: true })).toBeVisible();
        }
        await recibirCopia(1);
        await aprobador.getByRole("button", { name: "Revisar firma", exact: true }).click();
        await aprobador.getByLabel("Resultado de firma").click();
        await aprobador.getByRole("option", { name: "Rechazar copia y pedir corrección" }).click();
        await aprobador.getByLabel("Observaciones", { exact: false }).fill("Falta una firma en el anexo sintético de pruebas.");
        await aprobador.getByRole("checkbox").check();
        await aprobador.getByRole("button", { name: "Confirmar rechazo de copia" }).click();
        await expect(aprobador.getByText("Copia rechazada", { exact: true })).toBeVisible();
        await recibirCopia(2);
        await aprobador.getByRole("button", { name: "Revisar firma", exact: true }).click();
        await expect(aprobador.getByLabel("Observaciones", { exact: false })).toHaveValue("");
        await expect(aprobador.getByRole("checkbox").nth(0)).not.toBeChecked();
        await expect(aprobador.getByRole("checkbox").nth(1)).not.toBeChecked();
        await aprobador.getByRole("checkbox").nth(0).check();
        await aprobador.getByRole("checkbox").nth(1).check();
        await aprobador.getByRole("button", { name: "Aceptar firma y formalizar QA", exact: true }).click();
        await expect(aprobador.getByText("Formalizada en QA.", { exact: true })).toBeVisible();
        await expect(aprobador.getByText("Copia rechazada", { exact: true })).toBeVisible();
        await expect(aprobador.getByText("Firma aceptada", { exact: true })).toBeVisible();
        await aprobador.evaluate(() => scrollTo(0, 0));
        await aprobador.screenshot({ path: testInfo.outputPath("firma-qa-desktop.png"), fullPage: true });
        await aprobador.setViewportSize({ width: 390, height: 844 });
        await expect.poll(() => aprobador.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
        await aprobador.evaluate(() => scrollTo(0, 0));
        await aprobador.screenshot({ path: testInfo.outputPath("firma-qa-mobile.png"), fullPage: true });
        await aprobador.setViewportSize({ width: 1440, height: 1000 });
        await aprobador.getByRole("link", { name: "Registrar desembolso QA", exact: true }).click();
        await expect(aprobador.getByRole("heading", { name: "Registrar desembolso", exact: true })).toBeVisible();
        await expect(aprobador.locator('.p-message').first()).toHaveCSS("opacity", "1");
        await aprobador.screenshot({ path: testInfo.outputPath("desembolso-qa-desktop.png"), fullPage: true });
        await aprobador.getByRole("button", { name: "Revisar y registrar desembolso QA" }).click();
        await aprobador.getByLabel("Referencia única de transferencia", { exact: false }).fill("QA-TRANSFERENCIA-E2E-001");
        await aprobador.getByRole("checkbox").check();
        await aprobador.getByRole("button", { name: "Confirmar registro QA" }).click();
        await expect(aprobador).toHaveURL(/\/creditos\/\d+$/);
        await expect(aprobador.getByRole("heading", { name: "Desembolso registrado", exact: true })).toBeVisible();
        await expect(aprobador.getByText("Referencia: QA-TRANSFERENCIA-E2E-001", { exact: true })).toBeVisible();
        await aprobador.screenshot({ path: testInfo.outputPath("credito-qa-desktop.png"), fullPage: true });
        await aprobador.setViewportSize({ width: 390, height: 844 });
        await expect.poll(() => aprobador.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
        await aprobador.screenshot({ path: testInfo.outputPath("credito-qa-mobile.png"), fullPage: true });
        assertApproverConsole();
    } finally {
        await context.close();
    }
    await page.getByRole("button", { name: "Actualizar datos de la solicitud" }).click();
    await expect(page.getByRole("heading", { name: "Desembolsada · QA", exact: true })).toBeVisible();
    assertConsole();
});
