<script setup>
import { Link } from "@inertiajs/vue3";
import AppLayout from "@sakai-vue/layout/AppLayout.vue";
import SimulationTaxSummary from "@/Components/Products/SimulationTaxSummary.vue";
import { formatMoneyWithCents as money } from "@/Pages/ProductosCrediticios/productValidation";
defineProps({ credito: Object, desembolso: Object, cronograma: Object, movimientos: Object, pagos: Object, situacion: Object, puedePagar: Boolean, puedeVerContrato: Boolean });
const fecha = value => value?.slice(0, 10);
const tipos = { capital_inicial: "Capital inicial", devengo: "Concepto devengado", impuesto: "Impuesto generado", pago_concepto: "Abono a concepto", pago_impuesto: "Abono a impuesto", reverso: "Reverso compensatorio" };
</script>
<template>
    <AppLayout :title="`Crédito CR-${credito.id}`">
        <template #card-content>
            <div class="space-y-6 p-4 md:p-6">
                <nav class="flex flex-wrap gap-4 text-sm" aria-label="Contexto del crédito"><Link :href="route('creditos.index')" class="text-primary hover:underline"><i class="pi pi-arrow-left mr-2" />Créditos</Link><Link :href="route('solicitudes.show', credito.solicitud_id)" class="text-primary hover:underline">Solicitud SOL-{{ credito.solicitud_id }}</Link><Link :href="route('clientes.expediente.show', credito.cliente_id)" class="text-primary hover:underline">Expediente del cliente</Link><Link v-if="puedeVerContrato" :href="route('solicitudes.paquete.show', credito.solicitud_id)" class="text-primary hover:underline">Contrato y firma</Link></nav>
                <header><p class="text-xs font-semibold uppercase tracking-widest text-primary">Crédito simple · MXN</p><h1 class="mt-2 text-2xl font-bold">Crédito CR-{{ credito.id }}</h1><p class="mt-2 text-surface-500">{{ credito.cliente.primer_nombre }} {{ credito.cliente.apellido_paterno }} · {{ credito.sucursal.nombre }}</p></header>
                <section class="rounded-2xl bg-gradient-to-br from-slate-950 to-violet-700 p-6 text-white" aria-label="Resumen del crédito">
                    <Tag value="Activo · QA" severity="success" /><h2 class="mt-4 text-xl font-semibold text-white">Desembolso registrado</h2>
                    <div class="mt-5 grid gap-4 sm:grid-cols-3"><div class="rounded-xl bg-white/10 p-4"><p>Efectivo entregado</p><p class="mt-2 text-2xl font-bold">{{ money(desembolso.importe) }}</p></div><div class="rounded-xl bg-white/10 p-4"><p>Capital inicial registrado</p><p class="mt-2 text-2xl font-bold">{{ money(credito.capital_inicial) }}</p></div><div class="rounded-xl bg-white/10 p-4"><p>Fecha efectiva</p><p class="mt-2 text-xl font-semibold">{{ fecha(desembolso.fecha_efectiva) }}</p></div></div>
                </section>
                <section class="space-y-4 rounded-2xl border border-surface-200 p-5 dark:border-surface-700" aria-label="Situación actual">
                    <div class="flex flex-wrap items-center justify-between gap-3"><h2 class="text-lg font-semibold"><i class="pi pi-wallet mr-2 text-primary" aria-hidden="true" />Situación actual</h2><Link v-if="puedePagar" :href="route('creditos.pagos.create', credito.id)" class="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-3 font-semibold text-primary-contrast"><i class="pi pi-plus" aria-hidden="true" />Registrar pago QA</Link></div>
                    <Message v-if="situacion?.error" severity="warn" :closable="false">{{ situacion.error }} Las condiciones históricas no se actualizan automáticamente. Solicita revisión al administrador; para probar reglas nuevas utiliza un nuevo crédito QA.</Message>
                    <template v-if="situacion?.resumen">
                        <p class="text-sm text-surface-500">Calculado al {{ situacion.resumen.fecha }}. Los intereses futuros del calendario firmado no son deuda devengada.</p>
                        <div class="grid gap-3 sm:grid-cols-3"><div class="rounded-xl bg-primary-50 p-4 dark:bg-primary-950"><p>Capital pendiente</p><p class="mt-2 text-xl font-bold text-primary">{{ money(situacion.resumen.capital_insoluto) }}</p></div><div class="rounded-xl bg-surface-100 p-4 dark:bg-surface-800"><p>Exigible a esta fecha</p><p class="mt-2 text-xl font-bold">{{ money(situacion.resumen.exigible) }}</p></div><div class="rounded-xl bg-surface-100 p-4 dark:bg-surface-800"><p>Capital vencido</p><p class="mt-2 text-xl font-bold">{{ money(situacion.resumen.capital_vencido) }}</p><p class="text-sm">{{ situacion.resumen.dias_atraso }} días de atraso del capital</p></div></div>
                        <p class="text-sm text-surface-500">El registro exige revisar primero la distribución. No se admiten anticipos ni excedentes; un pago con fecha pasada se bloquea si existen movimientos posteriores.</p>
                    </template>
                </section>
                <section class="space-y-4 rounded-2xl border border-surface-200 p-5 dark:border-surface-700"><h2 class="text-lg font-semibold"><i class="pi pi-receipt mr-2 text-primary" />Pagos y reversos</h2><DataTable :value="pagos?.data || []" scrollable><template #empty>Aún no hay pagos registrados. El desembolso no cuenta como pago del cliente.</template><Column header="Comprobante"><template #body="{data}"><Link :href="route('creditos.pagos.show', [credito.id, data.id])" class="font-semibold text-primary hover:underline">{{ data.tipo === 'reverso' ? 'Reverso' : 'Pago' }} #{{ data.id }}</Link></template></Column><Column header="Fecha efectiva"><template #body="{data}">{{ fecha(data.fecha_efectiva) }}</template></Column><Column header="Importe"><template #body="{data}">{{ money(data.importe) }}</template></Column></DataTable><nav class="flex justify-between" aria-label="Páginas de pagos"><Link v-if="pagos?.prev_page_url" :href="pagos.prev_page_url" preserve-scroll class="text-primary">Anteriores</Link><Link v-if="pagos?.next_page_url" :href="pagos.next_page_url" preserve-scroll class="text-primary">Siguientes</Link></nav></section>
                <div class="grid gap-5 md:grid-cols-2">
                    <section class="space-y-3 rounded-2xl border border-surface-200 p-5 dark:border-surface-700"><h2 class="font-semibold"><i class="pi pi-send mr-2 text-primary" />Transferencia manual QA</h2><p class="break-all">Referencia: {{ desembolso.referencia }}</p><p>Registrado el {{ new Date(desembolso.created_at).toLocaleString('es-MX') }} · usuario #{{ desembolso.registrado_por }}</p><p class="text-sm text-surface-500">No se ejecutó una transferencia bancaria. El registro es inmutable; no lo borres ni repitas para corregirlo.</p></section>
                    <section class="space-y-3 rounded-2xl border border-surface-200 p-5 dark:border-surface-700"><h2 class="font-semibold"><i class="pi pi-lock mr-2 text-primary" />Condiciones conservadas</h2><p>Responsable: {{ credito.responsable.name }}</p><p>Calendario versión {{ cronograma.version }} · tomado de la firma</p><p class="break-all text-xs text-surface-500">Huella: {{ cronograma.snapshot_hash }}</p><p class="text-sm text-surface-500">Cambiar el producto o la plantilla no cambia este crédito. Los ajustes posteriores requerirán operaciones trazables.</p></section>
                </div>
                <section class="space-y-4 rounded-2xl border border-surface-200 p-5 dark:border-surface-700"><h2 class="text-lg font-semibold">Calendario firmado · proyección</h2><SimulationTaxSummary :simulation="cronograma.tabla" />
                    <DataTable :value="cronograma.tabla.tabla" paginator :rows="10" stripedRows scrollable><Column field="numero" header="#" /><Column field="fecha" header="Fecha" /><Column v-for="col in [{key:'capital',label:'Capital'},{key:'interes',label:'Interés'},{key:'comisiones',label:'Comisiones'},{key:'impuestos',label:'Impuestos'},{key:'pago_total',label:'Total proyectado'}]" :key="col.key" :header="col.label"><template #body="{data}">{{ money(data[col.key]) }}</template></Column></DataTable>
                </section>
                <section class="space-y-4 rounded-2xl border border-surface-200 p-5 dark:border-surface-700"><h2 class="text-lg font-semibold">Movimientos registrados</h2><p class="text-sm text-surface-500">Los cargos aumentan la deuda; los abonos la reducen. Los devengos se registran al aplicar pagos, mientras que la situación actual se calcula a la fecha de consulta. Un reverso conserva y compensa el registro original.</p><DataTable :value="movimientos.data" scrollable><Column header="Movimiento"><template #body="{data}">{{ tipos[data.tipo] || data.tipo }}</template></Column><Column field="concepto" header="Concepto" /><Column header="Fecha efectiva"><template #body="{data}">{{ fecha(data.fecha_efectiva) }}</template></Column><Column header="Importe"><template #body="{data}">{{ money(data.importe) }}</template></Column><Column field="actor_id" header="Usuario" /></DataTable><nav class="flex justify-between" aria-label="Páginas de movimientos"><Link v-if="movimientos.prev_page_url" :href="movimientos.prev_page_url" preserve-scroll class="text-primary">Anteriores</Link><Link v-if="movimientos.next_page_url" :href="movimientos.next_page_url" preserve-scroll class="text-primary">Siguientes</Link></nav></section>
            </div>
        </template>
    </AppLayout>
</template>
